"""исходная схема

Ревизия: 31524c3df3fe
Предыдущая: 
Создана: 2026-10-02 10:13:05.342179
"""
from alembic import op
import sqlalchemy as sa


revision = '31524c3df3fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('details', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_log_created_at'), ['created_at'], unique=False)

    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('place', sa.String(length=40), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('route_tags', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('collectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('logo', sa.String(length=300), nullable=True),
    sa.Column('lead', sa.String(length=300), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contacts', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('file', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('size_kb', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('slug', sa.String(length=400), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('lead', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('show_media', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_published_at'), ['published_at'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('show_in_menu', sa.Boolean(), nullable=False),
    sa.Column('template', sa.String(length=32), nullable=True),
    sa.Column('seo_description', sa.String(length=400), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('map_embed', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('poster', sa.String(length=300), nullable=True),
    sa.Column('cover', sa.String(length=300), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('age_limit', sa.String(length=8), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('performers', sa.Text(), nullable=True),
    sa.Column('organizer', sa.String(length=300), nullable=True),
    sa.Column('ticket_url', sa.String(length=500), nullable=True),
    sa.Column('tickets_left', sa.String(length=80), nullable=True),
    sa.Column('hall_widget', sa.Text(), nullable=True),
    sa.Column('show_pushkin', sa.Boolean(), nullable=False),
    sa.Column('pushkin_text', sa.Text(), nullable=True),
    sa.Column('show_benefits', sa.Boolean(), nullable=False),
    sa.Column('benefits_text', sa.Text(), nullable=True),
    sa.Column('show_media', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_starts_at'), ['starts_at'], unique=False)

    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=False),
    sa.Column('hint', sa.String(length=400), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('style', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_collectives',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('collective_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collective_id'], ['collectives.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'collective_id')
    )
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('file', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('embed', sa.Text(), nullable=True),
    sa.Column('preview', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('collective_id', sa.Integer(), nullable=True),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collective_id'], ['collectives.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_items')
    op.drop_table('event_collectives')
    op.drop_table('event_badges')
    op.drop_table('menu_items')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_starts_at'))

    op.drop_table('events')
    op.drop_table('venues')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('pages')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_published_at'))

    op.drop_table('news')
    op.drop_table('documents')
    op.drop_table('collectives')
    op.drop_table('categories')
    op.drop_table('banners')
    op.drop_table('appeals')
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_log_created_at'))

    op.drop_table('action_log')
    # ### end Alembic commands ###
